name: Generate Javadocs

on:
  push:
    branches:
      - main  # Adjust to your primary branch (e.g., main, master)

jobs:
  generate-javadoc:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'  # Replace with your Java version (e.g., 11, 17)
          distribution: 'temurin'

      # Step 3: Ensure the directory exists and list the content
      - name: Check if directory exists
        run: |
          echo "Checking if the miniverdener_docs directory exists"
          ls -la ./code

      # Step 4: Generate Javadocs
      - name: Generate Javadocs
        run: |
          echo "Running Javadoc command..."
          javadoc -d ./code/miniverdener_docs -sourcepath ./code/src ./code/src/*.java

      # Debugging step: List generated Javadoc folder contents after generation
      - name: List generated Javadoc folder contents
        run: |
          echo "Listing contents of the generate
